name = "TFI Hub"
license = "MIT"
licenselink = "https://github.com/andorsk/tfi-hub/blob/main/LICENSE"
description = "We're all about using technology to make a real difference."
homepage = "https://github.com/andorsk/tfi-hub"
demosite = "https://zeon.studio/preview?project=hugoplate"
min_version = "0.121.2"

tags = [
  "blog",
  "responsive",
  "minimal",
  "personal",
  "light",
  "dark",
  "multilingual",
  "landing",
  "contact",
  "dark mode",
  "tailwindcss",
]

features = [
  "Multi-Authors",
  "Search",
  "Multilingual",
  "Dark Mode",
  "Taxonomies",
]

[author]
name = "TFI Hub"
homepage = ""

[original]
author = "TFI Hub"
homepage = "https://zeon.studio"
repo = "https://github.com/zeon-studio/themeplate"
